myapp:
 data: Config Server Default
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mytracker
  data:
    rest:
      base-path: /api/v2
eureka:
	client:
	  registerWithEureka: false
   serviceUrl:
    defaultZone: http://localhost:8082/eureka/
	  fetchRegistry: false
	server:
	  waitTimeInMsWhenSyncEmpty: 0      
      
 
 
 
 
